public enum BannerAdSizeEnum: String {
    case BANNER = "BANNER"
    case FULL_BANNER = "FULL_BANNER"
    case LARGE_BANNER = "LARGE_BANNER"
    case LEADERBOARD = "LEADERBOARD"
    case MEDIUM_RECTANGLE = "MEDIUM_RECTANGLE"
    case WIDE_SKYSCRAPER = "WIDE_SKYSCRAPER"
    case ADAPTIVE_BANNER = "ADAPTIVE_BANNER"
    //    case FLUID = "FLUID"
}
